language: rust
#sudo: false

cache: cargo

matrix:
  include:

    # Builds on nightly.
    - rust: nightly
      env: RUST_BACKTRACE=1
      before_install:
        - nvm install 14.15.3
        - nvm install-latest-npm
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        - rustup target add wasm32-unknown-unknown
        - rustup component add rust-src
      script:
        - node -v
        - cd rust && wasm-pack build
        - cd ../app && npm ci && npm run-script build && cd ..
      deploy:
        provider: script
        edge: true
        script: netlify deploy --dir=app/dist --prod
        on:
          branch: master

